"""Unified CVE modules: each cve_*.py exposes scan() and exploit()."""

from modules.cves.metadata import (
    APP_KEY_PRODUCERS,
    CVE_META,
    CVE_METADATA,
    CVE_SCOPE,
    LAB_DEFAULT_APP_KEYS,
    LAB_DEFAULT_CREDS,
    SEV_RANK,
    all_cves,
    all_slugs,
    cves_by_criticality,
    detector_spec_for,
    detector_specs_for,
    force_requested,
    import_cve_module,
    import_exploit,
    import_scan,
    lab_default_app_key_for,
    lab_default_creds_for,
    metadata_dict_for,
    metadata_for,
    module_path_for,
    requires_component_map,
    scope_of,
    slug_for,
    version_suppresses,
)

__all__ = [
    "APP_KEY_PRODUCERS",
    "CVE_META",
    "CVE_METADATA",
    "CVE_SCOPE",
    "LAB_DEFAULT_APP_KEYS",
    "LAB_DEFAULT_CREDS",
    "SEV_RANK",
    "all_cves",
    "all_slugs",
    "cves_by_criticality",
    "detector_spec_for",
    "detector_specs_for",
    "force_requested",
    "import_cve_module",
    "import_exploit",
    "import_scan",
    "lab_default_app_key_for",
    "lab_default_creds_for",
    "metadata_dict_for",
    "metadata_for",
    "module_path_for",
    "requires_component_map",
    "scope_of",
    "slug_for",
    "version_suppresses",
]
