"""Generator helpers namespace."""

from .livewire_filemanager_endpoints import (
    FILEMANAGER_AUX_PATHS,
    FILEMANAGER_UPLOAD_PATHS,
    LIVEWIRE_UPLOAD_ENDPOINTS,
    FILEMANAGER_COMPONENT_PATHS,
    ADMIN_REPORT_PATHS,
    CVE_2024_47823_EXTRA_PATH_HINTS,
    CVE_2025_14894_EXTRA_PATH_HINTS,
)

__all__ = [
    "FILEMANAGER_AUX_PATHS",
    "FILEMANAGER_UPLOAD_PATHS",
    "LIVEWIRE_UPLOAD_ENDPOINTS",
    "FILEMANAGER_COMPONENT_PATHS",
    "ADMIN_REPORT_PATHS",
    "CVE_2024_47823_EXTRA_PATH_HINTS",
    "CVE_2025_14894_EXTRA_PATH_HINTS",
]
