"""Shared endpoint/catalog hints for Livewire upload and file-manager exploitation paths."""

from __future__ import annotations

from typing import Iterable, Tuple


def _dedupe_paths(*paths: Iterable[str]) -> Tuple[str, ...]:
    """Return values in first-seen order while removing duplicates.

    Historically this helper was called with a single tuple argument (e.g.
    ``_dedupe_paths(_FILEMANAGER_UPLOAD_PATHS)``), so it now treats any nested
    tuple/list as a nested block and flattens one level before deduping.
    """
    seen = set()
    out = []

    def _walk(values):
        if values is None:
            return
        if isinstance(values, str):
            if values not in seen:
                seen.add(values)
                out.append(values)
            return
        if isinstance(values, (list, tuple)):
            for child in values:
                _walk(child)
            return
        try:
            value = str(values)
        except Exception:
            return
        if value not in seen:
            seen.add(value)
            out.append(value)

    for path in paths:
        _walk(path)
    return tuple(out)


# Canonical baseline upload surfaces observed across production and OSS Laravel apps.
_FILEMANAGER_UPLOAD_PATHS = (
    "/",
    "/upload",
    "/uploads",
    "/upload-file",
    "/upload_logo",
    "/upload-logo",
    "/upload-logo/",
    "/upload-file/logo",
    "/file-upload",
    "/upload",
    "/upload/logo",
    "/file-manager",
    "/file-manager/upload",
    "/file-manager/uploads",
    "/file-manager/file",
    "/file-manager/file-upload",
    "/file-uploads",
    "/file-library",
    "/file-library/upload",
    "/file-library/files",
    "/filelibrary",
    "/filelibrary/upload",
    "/filelibrary/files",
    "/files",
    "/files/upload",
    "/files/file",
    "/filemanager",
    "/filemanager/upload",
    "/filemanager/uploads",
    "/filemanager/file",
    "/filemanager/filemanager",
    "/filemanager-upload",
    "/filemanager/uploads",
    "/admin/filemanager",
    "/admin/file-manager",
    "/admin/filemanager/upload",
    "/admin/file-manager/upload",
    "/admin/file-manager-list",
    "/admin/file-manager/list",
    "/admin/filemanager/list",
    "/admin/file-manager/files",
    "/admin/filemanager/files",
    "/admin/file-upload",
    "/admin/upload",
    "/admin/uploads",
    "/admin/file-uploads",
    "/admin/file_manager",
    "/admin/file_manager/upload",
    "/admin/file-manager-list",
    "/admin/file-library",
    "/admin/file-library/upload",
    "/admin/file-library/list",
    "/admin/file-library/file",
    "/admin/media-library",
    "/admin/media-library/upload",
    "/admin/media-library/list",
    "/admin/media-library/file",
    "/admin/medialibrary",
    "/admin/media-manager",
    "/admin/media-manager/upload",
    "/admin/media-manager/list",
    "/admin/media-manager/file",
    "/admin/media",
    "/admin/media/files",
    "/admin/media/file",
    "/admin/files",
    "/admin/files/upload",
    "/admin/files/list",
    "/admin/file-browser",
    "/admin/filebrowser",
    "/admin/file-uploader",
    "/admin/fileupload",
    "/admin/fileupload/upload",
    "/admin/livewire",
    "/admin/livewire/upload",
    "/admin/livewire/upload-file",
    "/admin/livewire/file-upload",
    "/admin/livewire-file-upload",
    "/admin/livewire/message",
    "/admin/livewire/message/upload",
    "/admin/livewire-filemanager",
    "/admin/livewire-file-manager",
    "/admin/livewire/file-upload",
    "/admin/laravel-filemanager",
    "/admin/laravel-file-manager",
    "/admin/laravel-filemanager/upload",
    "/admin/laravel-file-manager/upload",
    "/admin/elfinder",
    "/admin/elfinder/connector",
    "/admin/elfinder/file",
    "/admin/elfinder/elfinder.html",
    "/admin/lfm",
    "/admin/lfm/upload",
    "/admin/filemanager/upload",
    "/admin/file-manager/upload",
    "/admin/file-managers",
    "/admin/tran_es/report",
    "/admin/tran_es/report.html",
    "/admin/report",
    "/admin/report.html",
    "/admin/reports",
    "/admin/reports.html",
    "/admin/queue",
    "/admin/queue/monitor",
    "/admin/queue/list",
    "/admin/queue/status",
    "/admin/queue/failed",
    "/admin/queue/work",
    "/admin/queue/jobs",
    "/admin/media-manager/file",
    "/admin/storage",
    "/admin/storage-link",
    "/admin/storage/link",
    "/admin/ckfinder",
    "/admin/ckfinder/ckfinder.html",
    "/admin/ckfinder/connector",
    "/admin/ckfinder/core/connector/php/connector.php",
    "/admin/ckfinder/core/connector/php/connector.minimal.php",
    "/vendor/ckfinder/ckfinder.html",
    "/vendor/ckfinder/core/connector/php/connector.php",
    "/vendor/ckfinder/core/connector/php/connector.minimal.php",
    "/ckfinder",
    "/ckfinder/ckfinder.html",
    "/ckfinder/connector",
    "/ckfinder/core/connector/php/connector.php",
    "/ckfinder/core/connector/php/connector.minimal.php",
    "/assets/filemanager",
    "/backend/filemanager",
    "/backend/file-manager",
    "/backend/file-manager/upload",
    "/backend/laravel-filemanager",
    "/backend/laravel-file-manager",
    "/backend/laravel-filemanager/upload",
    "/backend/laravel-file-manager/upload",
    "/backend/media",
    "/backend/media-manager",
    "/backend/media/files",
    "/backend/lfm",
    "/backend/lfm/upload",
    "/laravel-filemanager",
    "/laravel-file-manager",
    "/lfm",
    "/media",
    "/media-manager",
    "/media-manager/upload",
    "/media-manager/file",
    "/media/files",
    "/media/file",
    "/media-library",
    "/media-library/upload",
    "/media-library/files",
    "/media-library/list",
    "/media-browser",
    "/media-browser/upload",
    "/media-browser/file",
    "/livewire-file-manager",
    "/livewire-filemanager",
    "/livewire/upload",
    "/livewire/upload-file",
    "/livewire/upload-image",
    "/_livewire/upload",
    "/_livewire/upload-file",
    "/livewire/message",
    "/livewire/message/upload",
    "/_livewire/message",
    "/_livewire/message/upload",
    "/livewire/update",
    "/_livewire/update",
    "/api/upload",
    "/api/v1/upload",
    "/api/v2/upload",
    "/api/media",
    "/api/media/upload",
    "/api/file",
    "/api/file/upload",
    "/api/files",
    "/api/files/upload",
    "/api/upload-logo",
    "/api/v1/company/upload-logo",
    "/api/v2/media/upload",
    "/v1/upload",
    "/v2/upload",
    "/upload.php",
    "/media.php",
    "/storage/upload",
    "/public/laravel-filemanager",
    "/public/filemanager",
    "/public/media",
)
FILEMANAGER_UPLOAD_PATHS = _dedupe_paths(_FILEMANAGER_UPLOAD_PATHS)

# Endpoint aliases and storage-facing route aliases commonly adjacent to filemanager surfaces.
_FILEMANAGER_AUX_PATHS = (
    "/media-manager/file",
    "/media-manager/upload",
    "/filemanager/file",
    "/filemanager/filemanager",
    "/laravel-filemanager/filemanager",
    "/admin/media-manager/upload",
    "/admin/media-manager/file",
    "/admin/lfm/upload",
    "/backend/lfm",
    "/backend/lfm/upload",
    "/assets/media",
    "/admin/file_manager/file",
    "/admin/media-library/file",
    "/admin/file-library/file",
    "/admin/elfinder/file",
    "/admin/fileupload/file",
    "/admin/file-manager/list",
    "/admin/filemanager/list",
    "/admin/media-manager/list",
    "/admin/media-library/list",
    "/admin/file-library/list",
    "/admin/report",
    "/admin/report.html",
    "/admin/reports",
    "/admin/reports.html",
    "/admin/queue/list",
    "/admin/queue/status",
    "/admin/queue/failed",
    "/admin/storage",
    "/elfinder/file",
    "/elfinder/connector",
    "/elfinder/elfinder.html",
    "/media-library/file",
    "/media-library/upload",
    "/media/library",
    "/livewire/message",
    "/_livewire/message",
    "/admin/livewire/message",
    "/admin/_livewire/message",
)
FILEMANAGER_AUX_PATHS = _dedupe_paths(_FILEMANAGER_AUX_PATHS)

# Additional endpoint families used by CVE-2024-47823 upload POST-path probing.
_LIVEWIRE_UPLOAD_ENDPOINTS = (
    "/livewire/upload",
    "/livewire/upload-file",
    "/livewire/upload-image",
    "/livewire/file-upload",
    "/livewire-file-upload",
    "/_livewire/upload",
    "/_livewire/upload-file",
    "/admin/livewire/upload",
    "/admin/livewire-file-upload",
    "/admin/livewire/file-upload",
    "/admin/livewire/upload-file",
    "/admin/livewire/message/upload",
    "/admin/_livewire/message/upload",
    "/admin/livewire/message",
    "/admin/_livewire/message",
    "/livewire/message",
    "/livewire/message/upload",
    "/_livewire/message",
    "/_livewire/message/upload",
    "/admin/file-upload",
    "/admin/file-manager/upload",
    "/admin/filemanager/upload",
    "/admin/media/upload",
    "/admin/media-manager/upload",
    "/admin/media-library/upload",
    "/admin/file-upload",
    "/admin/file-upload/logo",
    "/admin/tran_es/report",
    "/admin/tran_es/report.html",
    "/admin/storage-link",
    "/admin/storage/link",
    "/admin/queue",
    "/admin/queue/monitor",
    "/admin/ckfinder/ckfinder.html",
    "/vendor/ckfinder/ckfinder.html",
    "/admin/elfinder/connector",
    "/admin/elfinder/elfinder.html",
    "/admin/file-library/upload",
    "/admin/files/upload",
    "/admin/file-browser/upload",
    "/admin/file-manager/file",
    "/admin/lfm/upload",
    "/admin/laravel-filemanager/upload",
    "/admin/laravel-file-manager/upload",
    "/admin/upload-logo",
    "/admin/media-manager/file",
    "/admin/file-library/file",
    "/api/media/upload",
    "/api/file/upload",
)
LIVEWIRE_UPLOAD_ENDPOINTS = _dedupe_paths(_LIVEWIRE_UPLOAD_ENDPOINTS)

# Candidate component/page paths for probing reachable upload surfaces.
_FILEMANAGER_COMPONENT_PATHS = (
    "/",
    "/file-manager",
    "/filemanager",
    "/admin/file-manager",
    "/admin/filemanager",
    "/admin/file-manager/upload",
    "/admin/filemanager/upload",
    "/admin/file-manager-list",
    "/admin/file-manager/list",
    "/admin/filemanager/list",
    "/admin/media-manager",
    "/admin/media",
    "/admin/media-manager/upload",
    "/admin/media-library",
    "/admin/elfinder",
    "/admin/elfinder/elfinder.html",
    "/admin/lfm",
    "/backend/filemanager",
    "/backend/file-manager",
    "/backend/laravel-filemanager",
    "/backend/laravel-file-manager",
    "/backend/media",
    "/backend/media-manager",
    "/media-manager",
    "/media",
    "/media/files",
    "/media-library",
    "/files",
    "/uploads",
    "/upload",
    "/file-upload",
    "/upload-file",
    "/upload-logo",
    "/upload_logo",
    "/laravel-filemanager",
    "/laravel-file-manager",
    "/lfm",
    "/livewire-filemanager",
    "/livewire-file-manager",
    "/ckfinder",
    "/admin/ckfinder",
    "/admin/ckfinder/ckfinder.html",
    "/vendor/ckfinder/ckfinder.html",
    "/admin/tran_es/report",
    "/admin/tran_es/report.html",
    "/admin/report",
    "/admin/report.html",
    "/admin/reports",
    "/admin/reports.html",
    "/admin/queue/monitor",
    "/admin/storage-link",
    "/admin/storage/link",
    "/admin/storage",
)
FILEMANAGER_COMPONENT_PATHS = _dedupe_paths(_FILEMANAGER_COMPONENT_PATHS)


# Route-family surfaces that usually gate file-manager/read-access/report pages.
ADMIN_REPORT_PATHS: Tuple[str, ...] = ("/admin/tran_es/report", "/admin/tran_es/report.html")


# Additional coverage-only route hints for CVE-2024-47823 public upload discovery.
# These are fed into reachable-component sweeps to reduce misses on atypical panel
# layouts that don't use canonical upload URIs.
CVE_2024_47823_EXTRA_PATH_HINTS: Tuple[str, ...] = (
    # File-manager admin variants
    "/admin/filemanager",
    "/admin/file-manager",
    "/admin/file-manager/list",
    "/admin/filemanager/list",
    "/admin/file-manager-list",
    "/admin/file-manager/upload",
    "/admin/filemanager/upload",
    "/admin/file-manager-file",
    "/admin/file-manager/files",
    "/admin/media",
    "/admin/media-manager",
    "/admin/media-manager/upload",
    "/admin/media-manager/file",
    "/admin/media-manager/list",
    "/admin/media-library",
    "/admin/media-library/file",
    "/admin/media-library/list",
    "/admin/media-library/upload",
    "/admin/file-library",
    "/admin/file-library/file",
    "/admin/file-library/list",
    "/admin/file-library/upload",
    "/admin/file-browser",
    "/admin/file-browser/list",
    "/admin/file-browser/upload",
    "/admin/fileupload",
    "/admin/fileupload/upload",
    "/admin/fileupload/file",
    "/admin/upload-logo",
    "/admin/upload_logo",
    "/admin/upload-file",

    # Livewire upload routes frequently used by manager/admin skins
    "/admin/livewire",
    "/admin/livewire-file-upload",
    "/admin/livewire/file-upload",
    "/admin/livewire/upload",
    "/admin/livewire/upload-file",
    "/admin/livewire/message",
    "/admin/livewire/message/upload",
    "/admin/_livewire/message",
    "/admin/_livewire/message/upload",
    "/livewire/message",
    "/livewire/message/upload",
    "/_livewire/message",
    "/_livewire/message/upload",

    # File-manager helper/admin tooling routes
    "/admin/elfinder",
    "/admin/elfinder/file",
    "/admin/elfinder/connector",
    "/admin/elfinder/elfinder.html",
    "/admin/ckfinder",
    "/admin/ckfinder/ckfinder.html",
    "/admin/ckfinder/core/connector/php/connector.php",
    "/admin/ckfinder/core/connector/php/connector.minimal.php",
    "/vendor/ckfinder/ckfinder.html",
    "/vendor/ckfinder/core/connector/php/connector.php",
    "/vendor/ckfinder/core/connector/php/connector.minimal.php",
    "/admin/tran_es/report",
    "/admin/tran_es/report.html",
    "/admin/queue",
    "/admin/queue/monitor",
    "/admin/queue/list",
    "/admin/queue/jobs",
    "/admin/queue/status",
    "/admin/storage",
    "/admin/storage-link",
    "/admin/storage/link",
)


# Additional coverage-only route hints for CVE-2025-14894 component discovery.
# These focus on public file-manager entry points that are commonly reachable from
# admin/report panels but are not always in canonical demo paths.
CVE_2025_14894_EXTRA_PATH_HINTS: Tuple[str, ...] = (
    "/admin/file-manager",
    "/admin/filemanager",
    "/admin/file-manager/upload",
    "/admin/filemanager/upload",
    "/admin/file_manager",
    "/admin/file_manager/upload",
    "/admin/file-manager/list",
    "/admin/filemanager/list",
    "/admin/file-library",
    "/admin/file-library/file",
    "/admin/file-library/list",
    "/admin/file-library/upload",
    "/admin/file-upload",
    "/admin/files",
    "/admin/files/list",
    "/admin/files/upload",
    "/admin/laravel-filemanager",
    "/admin/laravel-file-manager",
    "/admin/laravel-filemanager/upload",
    "/admin/laravel-file-manager/upload",
    "/admin/lfm",
    "/admin/lfm/upload",
    "/admin/media-manager",
    "/admin/media-manager/file",
    "/admin/media-manager/upload",
    "/admin/media-library",
    "/admin/media-library/file",
    "/admin/media-library/list",
    "/admin/media-library/upload",
    "/admin/elfinder",
    "/admin/elfinder/file",
    "/admin/elfinder/connector",
    "/admin/elfinder/elfinder.html",
    "/admin/queue",
    "/admin/queue/monitor",
    "/admin/queue/list",
    "/admin/queue/jobs",
    "/admin/report",
    "/admin/report.html",
    "/admin/reports",
    "/admin/reports.html",
    "/admin/tran_es/report",
    "/admin/tran_es/report.html",
    "/admin/ckfinder",
    "/admin/ckfinder/ckfinder.html",
    "/admin/storage-link",
    "/admin/storage/link",
)
